### ISSUE TITLE
Update parsing for default arguments, enable full WDL parsing

### ISSUE THREAD

**Issue by ambrosejcarr** [broadinstitute/winstanley#10]
There are two issues that are limiting my ability to use this plugin to catch errors while I write: 

1. The plugin in not up to date with respect to some of the syntax available in WDL and runnable in Cromwell. (default arguments, array dereferences; I have not tested exhaustively). These will be flagged as errors in the plugin but be cleared by wdltool and run in Cromwell. 
2. [minor] Currently the plugin identifies only the first error and stops

Together these mean that the error detection does not really function, since I'll have a default argument high in my file which will prevent detection of real errors later in the workflow. 

Example (The "=" between default and 100000 gets highlighted as an error): 

```
task ExampleTask {
  File input_file
  Int? truncate_n

  command {
    # truncate the input file
    head -n ${default=100000 truncate_n} input_file > truncated_input_file.txt
    < ... do something with the code with real errors ... >

  }
}
```
Please let me know if more information is needed to act on this.

**Comment by danbills** [comment]
Hi @ambrosejcarr , do you perhaps have more example WDL that showcases your concerns w/ default arguments and array dereferences?  I'm looking to create a test but I would prefer to start w/ existing code than attempt to reproduce.

**Comment by danbills** [comment]
screenshots would work too

**Comment by ambrosejcarr** [comment]
The example above will demonstrate the problem with default arguments (the syntax highlighter will highlight the in-command default assignment on line 7). If you then make further (intentional) errors they will not be highlighted. I've since removed it from my code and squashed the commit so don't have the original wdl. 

This wdl will show the array deference highlight on line 151: 
https://github.com/HumanCellAtlas/skylab/blob/master/10x/generate_demo_data/generate_demo_data.wdl

**Comment by danbills** [comment]
I have to put this on the backburner but I'll poke at it in my free time

**Comment by cjllanwarne** [comment]
Look out for the winstanley update coming to the JetBrains repo in the next few days!
