### ISSUE TITLE
Brace matching adds an extra right brace

### ISSUE THREAD

**Issue by rgobbel** [broadinstitute/winstanley#26]
Typing a left curly brace now inserts a matching right brace. If you then enter a newline, you wind up with an extra right brace.

Scenario:

Type `task foo {` , get `task foo {}`

Immediately type a return, get:

`task foo {`
`}` 
`}`

**Comment by cjllanwarne** [comment]
Hey @rgobbel you're right, it seems that automatic brace-closing is triggering twice, once when the opening brace is typed and once when <kbd>Enter</kbd> is pressed. I'll investigate whether the plugin can be smarter about disabling the second trigger by default.

In the mean time, you can turn off braces-on-enter by opening `Preferences` and going to `Editor > General > Smart Keys` and turning off the `Insert pair '}'` under `Enter`.

**Comment by cjllanwarne** [comment]
Fixed in develop, will be available in release 0.1.9!

**Comment by cjllanwarne** [comment]
Fixed in 0.1.9 (pending JetBrains approval: https://plugins.jetbrains.com/plugin/8154-winstanley-wdl)

**Comment by rgobbel** [comment]
Thanks, confirming that that works now.
