### ISSUE TITLE
Variables defined in output not recognized by error checker in same output scope.

### ISSUE THREAD

**Issue by ambrosejcarr** [broadinstitute/winstanley#27]
This is admittedly a bit of a weird thing to do, but.. 

![screen shot 2017-10-25 at 9 47 13 am](https://user-images.githubusercontent.com/5239152/32002111-a5fdf2bc-b969-11e7-9aa9-85fa358239dc.png)

A picture is worth 19 words. :)

**Comment by cjllanwarne** [comment]
Fixed in 0.1.9 (pending JetBrains approval: https://plugins.jetbrains.com/plugin/8154-winstanley-wdl)
